### ISSUE TITLE
Is there any way to customize the timeout for requests ?

### ISSUE THREAD

**Issue by RexChengZhu** [guessi/kubernetes-dnsperf#1]
i got some query lost ,not sure if it's the timeout too short 
  Queries sent:         300000
  Queries completed:    299992 (100.00%)
  Queries lost:         8 (0.00%)

  Response codes:       NOERROR 299992 (100.00%)
  Average packet size:  request 61, response 121
  Run time (s):         60.000304
  Queries per second:   4999.841334

  Average Latency (s):  0.000459 (min 0.000090, max 0.045371)
  Latency StdDev (s):   0.000953

**Comment by guessi** [comment]
Hi @RexChengZhu ,

Thanks for giving chance to test my creation.

Note that default timeout would be `5 seconds` which should be long enough for DNS test.

```
$ dnsperf --help

DNS Performance Testing Tool
Version 2.13.1

...

  -t the timeout for query completion in seconds (default: 5) 

...
```

I've updated the scripts to support more flags passing (including `-t` for timeout setup) and also bump dnsperf to more recent version [2.13.1](https://github.com/DNS-OARC/dnsperf/blob/develop/CHANGES). Commit history could be found at https://github.com/guessi/kubernetes-dnsperf/commits/master

**Comment by guessi** [comment]
Hi @RexChengZhu ,

As there have no update from you for 3 weeks already, I believe the newly release version could address your needs.
I'm going to close this issue for now, thanks for your issue report.
